// themes.js — built-in theme presets and application defaults
// ─────────────────────────────────────────────────────────────────────────────

export const SETTINGS_KEY    = 'peartree-settings';
export const USER_THEMES_KEY = 'peartree-user-themes';

export const THEMES = {
      "Minimal": {
          canvasBgColor:    '#ffffff',
          branchColor:      '#444444',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#000000',
          tipSize:          '2',
          tipHaloSize:      '1',
          tipShapeColor:    '#ffffff',
          tipShapeBgColor:  '#000000',
          nodeSize:         '0',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#000000',
          nodeShapeBgColor: '#000000',
          axisColor:        '#444444',
          legendTextColor:  '#444444',
          selectedTipStrokeColor:       '#E06961',
          selectedTipFillColor:         '#E06961',
          selectedNodeStrokeColor:      '#19A699',
          selectedNodeFillColor:        '#19A699',
          tipHoverStrokeColor:          '#f5a700',
          tipHoverFillColor:            '#f5a700',
          nodeHoverStrokeColor:         '#f5a700',
          nodeHoverFillColor:           '#f5a700',
      },
      "Artic": {
          canvasBgColor:    '#02292e',
          branchColor:      '#19A699',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#f7eeca',
          tipSize:          '3',
          tipHaloSize:      '1',
          tipShapeColor:    '#B58901',
          tipShapeBgColor:  '#02292e',
          nodeSize:         '0',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#E06961',
          nodeShapeBgColor: '#02292e',
          axisColor:        '#f7eeca',
          legendTextColor:  '#f7eeca',
          selectedTipFillColor:    '#FFF4A9',
          selectedTipStrokeColor:   '#FFF4A9',
          selectedNodeFillColor:   '#FFC9C7',
          selectedNodeStrokeColor:       '#FFC9C7',
          tipHoverFillColor:       '#FFF4A9',
          tipHoverStrokeColor:     '#FFF4A9',
          nodeHoverFillColor:  '#FFC9C7',
          nodeHoverStrokeColor:    '#FFC9C7',
      },
      "BEAST": {
          canvasBgColor:    '#5A5F62',
          branchColor:      '#3B6F84',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#B1CBB8',
          tipSize:          '3',
          tipHaloSize:      '1',
          tipShapeColor:    '#B58901',
          tipShapeBgColor:  '#02292e',
          nodeSize:         '0',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#E06961',
          nodeShapeBgColor: '#02292e',
          axisColor:        '#B1CBB8',
          legendTextColor:  '#B1CBB8',
      },
      // // Warm pastels: Grand Budapest Hotel / Moonrise Kingdom palette
      // "Wes": {
      //     canvasBgColor:    '#f5edd6',
      //     branchColor:      '#7b3b5e',
      //     branchWidth:      '1',
      //     fontSize:         '11',
      //     labelColor:       '#4a2040',
      //     tipSize:          '4',
      //     tipHaloSize:      '2',
      //     tipShapeColor:    '#d4614b',
      //     tipShapeBgColor:  '#f5edd6',
      //     nodeSize:         '0',
      //     nodeHaloSize:     '2',
      //     nodeShapeColor:   '#b8962e',
      //     nodeShapeBgColor: '#f5edd6',
      //     axisColor:        '#4a2040',
      // },
      // Deep jewel tones: The Life Aquatic / Isle of Dogs palette
      "MCM": {
          canvasBgColor:    '#1e2d3a',
          branchColor:      '#edd59c',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#f4c9a8',
          tipSize:          '4',
          tipHaloSize:      '1',
          tipShapeColor:    '#e07b65',
          tipShapeBgColor:  '#1e2d3a',
          nodeSize:         '3',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#7dbfcc',
          nodeShapeBgColor: '#1e2d3a',
          axisColor:        '#edd59c',
          legendTextColor:  '#edd59c',
      },
      // Royal Tenenbaums: aged plaster, forest green, burgundy, tennis-ball gold
      "Tenenbaums": {
          canvasBgColor:    '#f0e8d8',
          branchColor:      '#2b4a2a',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#1c3220',
          tipSize:          '4',
          tipHaloSize:      '1',
          tipShapeColor:    '#a01830',
          tipShapeBgColor:  '#f0e8d8',
          nodeSize:         '2',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#c8a020',
          nodeShapeBgColor: '#f0e8d8',
          axisColor:        '#2b4a2a',
          legendTextColor:  '#2b4a2a',
      },
      // Fantastic Mr Fox: night earth, fox orange, rust, harvest green
      "Mr Fox": {
          canvasBgColor:    '#1a0d00',
          branchColor:      '#e87830',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#f0c060',
          tipSize:          '3',
          tipHaloSize:      '1',
          tipShapeColor:    '#c84a18',
          tipShapeBgColor:  '#1a0d00',
          nodeSize:         '3',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#508a28',
          nodeShapeBgColor: '#1a0d00',
          axisColor:        '#f0c060',
          legendTextColor:  '#f0c060',  
      },
      // The Darjeeling Limited: warm cream, saffron, cerulean, rust
      "Darjeeling": {
          canvasBgColor:    '#faf0d8',
          branchColor:      '#c87010',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#3a2010',
          tipSize:          '4',
          tipHaloSize:      '1',
          tipShapeColor:    '#1a5878',
          tipShapeBgColor:  '#faf0d8',
          nodeSize:         '0',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#c04428',
          nodeShapeBgColor: '#faf0d8',
          axisColor:        '#3a2010',
          legendTextColor:  '#3a2010',
      },
      // // Mid Century Modern – Birch: warm white, teak, avocado, harvest gold
      // "MCM Birch": {
      //     canvasBgColor:    '#f2ede0',
      //     branchColor:      '#5c3a1e',
      //     branchWidth:      '1',
      //     fontSize:         '11',
      //     labelColor:       '#2a1c10',
      //     tipSize:          '4',
      //     tipHaloSize:      '2',
      //     tipShapeColor:    '#5a7a2a',
      //     tipShapeBgColor:  '#f2ede0',
      //     nodeSize:         '0',
      //     nodeHaloSize:     '2',
      //     nodeShapeColor:   '#c88c24',
      //     nodeShapeBgColor: '#f2ede0',
      //     axisColor:        '#2a1c10',
      // },
      // // Mid Century Modern – Walnut: warm sand, burnt sienna, mustard, teal
      // "MCM Walnut": {
      //     canvasBgColor:    '#e8dcc8',
      //     branchColor:      '#8c4822',
      //     branchWidth:      '1',
      //     fontSize:         '11',
      //     labelColor:       '#3a1c0a',
      //     tipSize:          '4',
      //     tipHaloSize:      '2',
      //     tipShapeColor:    '#c89520',
      //     tipShapeBgColor:  '#e8dcc8',
      //     nodeSize:         '0',
      //     nodeHaloSize:     '2',
      //     nodeShapeColor:   '#2a6870',
      //     nodeShapeBgColor: '#e8dcc8',
      //     axisColor:        '#3a1c0a',
      // },
      // // Mid Century Modern – Eames: dark walnut, warm amber, turquoise, coral
      // "MCM Eames": {
      //     canvasBgColor:    '#1a1208',
      //     branchColor:      '#d08830',
      //     branchWidth:      '1',
      //     fontSize:         '11',
      //     labelColor:       '#f0d890',
      //     tipSize:          '4',
      //     tipHaloSize:      '2',
      //     tipShapeColor:    '#2a8878',
      //     tipShapeBgColor:  '#1a1208',
      //     nodeSize:         '0',
      //     nodeHaloSize:     '2',
      //     nodeShapeColor:   '#c44030',
      //     nodeShapeBgColor: '#1a1208',
      //     axisColor:        '#f0d890',
      // },
      "O'Toole": {
          canvasBgColor:    '#D8D4D3',
          branchColor:      '#7984BC',
          branchWidth:      '1',
          fontSize:         '11',
          labelColor:       '#7984BC',
          tipSize:          '4',
          tipHaloSize:      '1',
          tipShapeColor:    '#AF808B',
          tipShapeBgColor:  '#D8D4D3',
          nodeSize:         '3',
          nodeHaloSize:     '1',
          nodeShapeColor:   '#88B2BA',
          nodeShapeBgColor: '#D8D4D3',
          axisColor:        '#7984BC',
          legendTextColor:  '#7984BC',
          selectedTipFillColor:    '#7f3e4d',
          selectedTipStrokeColor:   '#7f3e4d',
          selectedNodeFillColor:   '#263b3f',
          selectedNodeStrokeColor:       '#263b3f',
          tipHoverFillColor:       '#7f3e4d',
          tipHoverStrokeColor:     '#7f3e4d',
          nodeHoverFillColor:  '#263b3f',
          nodeHoverStrokeColor:    '#263b3f',
      },
};

export const DEFAULTS = {
  theme:            'Artic',
  canvasBgColor:    '#ffffff',
  branchColor:      '#444444',
  branchWidth:      '1',
  fontSize:         '11',
  labelColor:       '#000000',
  tipSize:          '2',
  tipHaloSize:      '1',
  tipShapeColor:    '#ffffff',
  tipShapeBgColor:  '#000000',
  nodeSize:         '0',
  nodeHaloSize:     '1',
  nodeShapeColor:   '#000000',
  nodeShapeBgColor: '#000000',
  axisColor:        '#444444',
  legendTextColor:  '#444444',
  selectedLabelStyle:   'bold',
  selectedTipStrokeColor:       '#E06961',
  selectedTipFillColor:         '#E06961',
  selectedTipGrowthFactor:      '1',
  selectedTipMinSize:           '4',
  selectedTipFillOpacity:       '0',
  selectedTipStrokeWidth:       '4.5',
  selectedTipStrokeOpacity:     '0.75',
  selectedNodeStrokeColor:      '#19A699',
  selectedNodeFillColor:        '#19A699',
  selectedNodeGrowthFactor:     '1',
  selectedNodeMinSize:          '4',
  selectedNodeFillOpacity:      '0',
  selectedNodeStrokeWidth:      '4.5',
  selectedNodeStrokeOpacity:    '0.75',
  tipHoverStrokeColor:          '#f5a700',
  tipHoverFillColor:            '#f5a700',
  tipHoverGrowthFactor:         '1.2',
  tipHoverMinSize:              '5',
  tipHoverFillOpacity:          '0.5',
  tipHoverStrokeWidth:          '2',
  tipHoverStrokeOpacity:        '0.5',
  nodeHoverStrokeColor:         '#f5a700',
  nodeHoverFillColor:           '#f5a700',
  nodeHoverGrowthFactor:        '1.2',
  nodeHoverMinSize:             '5',
  nodeHoverFillOpacity:         '0.5',
  nodeHoverStrokeWidth:         '2',
  nodeHoverStrokeOpacity:       '0.5',
  axisFontSize:     '9',
  axisLineWidth:    '1',
  legendShow:         'right',
  legendFontSize:     '11',
  axisShow:           'off',
  axisDateAnnotation: '',
  axisMajorInterval:    'auto',
  axisMinorInterval:    'off',
  axisMajorLabelFormat: 'auto',
  axisMinorLabelFormat: 'off',
};
