// themes.js — built-in theme presets and application defaults
// ─────────────────────────────────────────────────────────────────────────────

export { TYPEFACES, buildFont } from './typefaces.js';

export const SETTINGS_KEY = 'peartree-settings';
export const USER_THEMES_KEY = 'peartree-user-themes';
export const DEFAULT_THEME_KEY = 'peartree-default-theme';

export const THEMES = {
    "Monochrome": { // fully specified base theme: all keys in REQUIRED_THEME_KEYS are defined here
        "canvasBgColor": "#ebe8e2",
        "branchColor": "#333231",
        "branchWidth": "1.5",
        "elbowRadius": "2",
        "fontSize": "11",
        "typeface": "Monospace",
        "typefaceStyle": "Regular",
        "labelColor": "#4b4b49",
        "selectedLabelStyle": "bold",
        "tipSize": "3",
        "tipHaloSize": "1",
        "tipShapeColor": "#ebe8e2",
        "tipShapeBgColor": "#4b4b49",
        "nodeSize": "3",
        "nodeHaloSize": "1",
        "nodeShapeColor": "#4b4b49",
        "nodeShapeBgColor": "#ebe8e2",
        "nodeBarsColor": "#333231",
        "tipHoverFillColor": "#f5a700",
        "tipHoverStrokeColor": "#f5a700",
        "tipHoverGrowthFactor": "1.5",
        "tipHoverMinSize": "6",
        "tipHoverFillOpacity": "0.6",
        "tipHoverStrokeWidth": "2",
        "tipHoverStrokeOpacity": "1",
        "nodeHoverFillColor": "#f5a700",
        "nodeHoverStrokeColor": "#f5a700",
        "nodeHoverGrowthFactor": "5",
        "nodeHoverMinSize": "20",
        "nodeHoverFillOpacity": "0.6",
        "nodeHoverStrokeWidth": "2",
        "nodeHoverStrokeOpacity": "1",
        "selectedTipFillColor": "#ffffff",
        "selectedTipStrokeColor": "#ffffff",
        "selectedTipGrowthFactor": "3.6",
        "selectedTipMinSize": "17",
        "selectedTipFillOpacity": "0.45",
        "selectedTipStrokeWidth": "0.5",
        "selectedTipStrokeOpacity": "0.6",
        "selectedNodeFillColor": "#ffffff",
        "selectedNodeStrokeColor": "#ffffff",
        "selectedNodeGrowthFactor": "2",
        "selectedNodeMinSize": "6",
        "selectedNodeFillOpacity": "0.5",
        "selectedNodeStrokeWidth": "3",
        "selectedNodeStrokeOpacity": "1",
        "axisColor": "#4b4b49",
        "axisFontSize": "9",
        "axisFontFamily": "",
        "axisFontStyle": "",
        "axisLineWidth": "1",
        "legendTextColor": "#4b4b49",
        "legendFontSize": "11",
        "legendFontFamily": "",
        "legendFontStyle": "",
        "rttAxisColor": "#4b4b49",
        "rttStatsBgColor": "#bfbcb9",
        "rttStatsTextColor": "#4b4b49",
        "rttRegressionColor": "#807e7c"
    },
    "Artic": {
        canvasBgColor: '#02292e',
        branchColor: '#19A699',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Helvetica Neue',
        typefaceStyle: 'Thin',
        labelColor: '#f7eeca',
        tipSize: '3',
        tipHaloSize: '1',
        tipShapeColor: '#B58901',
        tipShapeBgColor: '#02292e',
        nodeSize: '0',
        nodeHaloSize: '1',
        nodeShapeColor: '#E06961',
        nodeShapeBgColor: '#02292e',
        nodeBarsColor: '#2aa198',
        axisColor: '#f7eeca',
        legendTextColor: '#f7eeca',
        nodeBarsColor: '#E06961',
        rttAxisColor: '#f7eeca',
        rttStatsBgColor: '#011a1f',
        rttStatsTextColor: '#f7eeca',
        rttRegressionColor: '#19A699',
    },
    "BEAST": {
        canvasBgColor: '#02292e',
        branchColor: '#68a3bb',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Monospace',
        labelColor: '#B1CBB8',
        tipSize: '3',
        tipHaloSize: '1',
        tipShapeColor: '#CBB944',
        tipShapeBgColor: '#02292e',
        nodeSize: '0',
        nodeHaloSize: '1',
        nodeShapeColor: '#3B6F84',
        nodeShapeBgColor: '#02292e',
        axisColor: '#B1CBB8',
        legendTextColor: '#B1CBB8',
        nodeBarsColor: '#CBB944',
        selectedTipFillColor: '#FFF4A9',
        selectedTipStrokeColor: '#FFF4A9',
        selectedNodeFillColor: '#B1CBB8',
        selectedNodeStrokeColor: '#B1CBB8',
        rttAxisColor: '#B1CBB8',
        rttStatsBgColor: '#011a1e',
        rttStatsTextColor: '#B1CBB8',
        rttRegressionColor: '#68a3bb',
    },
    "O'Toole": {
        canvasBgColor: '#f4f3f3',
        branchColor: '#7984BC',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Helvetica Neue',
        typefaceStyle: 'Light',
        labelColor: '#7984BC',
        tipSize: '3',
        tipHaloSize: '1',
        tipShapeColor: '#AF808B',
        tipShapeBgColor: '#D8D4D3',
        nodeSize: '2',
        nodeHaloSize: '1',
        nodeShapeColor: '#88B2BA',
        nodeShapeBgColor: '#D8D4D3',
        axisColor: '#7984BC',
        legendTextColor: '#7984BC',
        nodeBarsColor: '#88B2BA',
        selectedTipFillColor: '#7f3e4d',
        selectedTipStrokeColor: '#7f3e4d',
        selectedNodeFillColor: '#263b3f',
        selectedNodeStrokeColor: '#263b3f',
        tipHoverFillColor: '#7f3e4d',
        tipHoverStrokeColor: '#7f3e4d',
        nodeHoverFillColor: '#263b3f',
        nodeHoverStrokeColor: '#263b3f',
        rttAxisColor: '#7984BC',
        rttStatsBgColor: '#dddcdb',
        rttStatsTextColor: '#7984BC',
        rttRegressionColor: '#88B2BA',
    },
    // Deep jewel tones: The Life Aquatic / Isle of Dogs palette
    "MCM": {
        canvasBgColor: '#1e2d3a',
        branchColor: '#edd59c',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Monospace',
        labelColor: '#f4c9a8',
        tipSize: '4',
        tipHaloSize: '1',
        tipShapeColor: '#e07b65',
        tipShapeBgColor: '#1e2d3a',
        nodeSize: '3',
        nodeHaloSize: '1',
        nodeShapeColor: '#7dbfcc',
        nodeShapeBgColor: '#1e2d3a',
        axisColor: '#edd59c',
        legendTextColor: '#edd59c',
        nodeBarsColor: '#7dbfcc',
        rttAxisColor: '#edd59c',
        rttStatsBgColor: '#121c24',
        rttStatsTextColor: '#edd59c',
        rttRegressionColor: '#7dbfcc',
    },
    // Royal Tenenbaums: aged plaster, forest green, burgundy, tennis-ball gold
    "Tenenbaums": {
        canvasBgColor: '#f0e8d8',
        branchColor: '#2b4a2a',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Monospace',
        labelColor: '#1c3220',
        tipSize: '3',
        tipHaloSize: '1',
        tipShapeColor: '#a01830',
        tipShapeBgColor: '#f0e8d8',
        nodeSize: '2',
        nodeHaloSize: '1',
        nodeShapeColor: '#c8a020',
        nodeShapeBgColor: '#f0e8d8',
        axisColor: '#2b4a2a',
        legendTextColor: '#2b4a2a',
        nodeBarsColor: '#a01830',
        rttAxisColor: '#2b4a2a',
        rttStatsBgColor: '#d8cfbf',
        rttStatsTextColor: '#1c3220',
        rttRegressionColor: '#2b4a2a',
    },
    // The Darjeeling Limited: warm cream, saffron, cerulean, rust
    "Darjeeling": {
        canvasBgColor: '#faf0d8',
        branchColor: '#c87010',
        branchWidth: '1',
        fontSize: '11',
        typeface: 'Monospace',
        labelColor: '#3a2010',
        tipSize: '4',
        tipHaloSize: '1',
        tipShapeColor: '#1a5878',
        tipShapeBgColor: '#faf0d8',
        nodeSize: '0',
        nodeHaloSize: '1',
        nodeShapeColor: '#c04428',
        nodeShapeBgColor: '#faf0d8',
        axisColor: '#3a2010',
        legendTextColor: '#3a2010',
        nodeBarsColor: '#1a5878',
        rttAxisColor: '#3a2010',
        rttStatsBgColor: '#e8d8c0',
        rttStatsTextColor: '#3a2010',
        rttRegressionColor: '#c87010',
    },
};

