// themes.js — built-in theme presets and application defaults
// ─────────────────────────────────────────────────────────────────────────────

export { TYPEFACES, buildFont } from './typefaces.js';

export const SETTINGS_KEY = 'peartree-settings';
export const USER_THEMES_KEY = 'peartree-user-themes';

export const DEFAULT_THEME = {
    // acts as the fallback base theme: all keys in REQUIRED_THEME_KEYS must be defined here, and other themes are allowed to be sparse overrides that inherit from this at applyTheme() time
        // Tree
        "canvasBgColor": "#ebe8e2",
        // Branches
        "branchColor": "#333231",
        "branchWidth": "1.5",
        "elbowRadius": "2",
        // Tip Labels
        "fontSize": "11",
        "labelColor": "#4b4b49",
        // Label Shapes
        "tipLabelShapeColor": "#aaaaaa",
        // Tip Shapes
        "tipSize": "3",
        "tipShapeColor": "#ebe8e2",
        "tipHaloSize": "1",
        "tipShapeBgColor": "#4b4b49",
        // Node Shapes
        "nodeSize": "3",
        "nodeShapeColor": "#4b4b49",
        "nodeHaloSize": "1",
        "nodeShapeBgColor": "#ebe8e2",
        // Node Labels
        "nodeLabelFontSize": "9",
        "nodeLabelTypefaceKey": "",
        "nodeLabelTypefaceStyle": "",
        "nodeLabelColor": "#aaaaaa",
        "nodeLabelSpacing": "4",
        // Node Bars
        "nodeBarsColor": "#333231",
        "nodeBarsWidth": "6",
        "nodeBarsFillOpacity": "0.22",
        "nodeBarsStrokeOpacity": "0.55",
        // Paint brush / clade-highlight colour picker
        "paintColour": "#ff8800",
        // Clade Highlights
        "cladeHighlightFillOpacity": "0.15",
        "cladeHighlightStrokeOpacity": "0.7",
        "cladeHighlightStrokeWidth": "1",
        "cladeHighlightColour": "#ffaa00",
        // Collapsed Clades
        "collapsedCladeFontSize": "11",
        "collapsedCladeTypefaceKey": "",
        "collapsedCladeTypefaceStyle": "",
        // Legend
        "legendTextColor": "#4b4b49",
        "legendFontSize": "11",
        "legendTypefaceKey": "",
        "legendTypefaceStyle": "",
        // Axis
        "axisColor": "#4b4b49",
        "axisFontSize": "9",
        "axisTypefaceKey": "",
        "axisTypefaceStyle": "",
        "axisLineWidth": "1",
        // Root-to-tip: regression line
        "rttRegressionStyle": "dash",
        "rttRegressionColor": "#807e7c",
        "rttRegressionWidth": "1.5",
        // Root-to-tip: residual band (±2σ)
        "rttResidBandColor":       "#807e7c",
        "rttResidBandStyle":       "dash",
        "rttResidBandWidth":       "1",
        "rttResidBandFillColor":   "#807e7c",
        "rttResidBandFillOpacity": "0.1",
        // Root-to-tip: statistics box
        "rttStatsBgColor": "#bfbcb9",
        "rttStatsTextColor": "#4b4b49",
        "rttStatsFontSize": "11",
        // Root-to-tip: axes
        "rttAxisColor": "#4b4b49",
        "rttAxisFontSize": "9",
        "rttAxisLineWidth": "1",
        "rttAxisTypefaceKey": "",
        "rttAxisTypefaceStyle": "",
        // Theme (global typeface)
        "typeface": "Monospace",
        "typefaceStyle": "Regular",
        // Selection & Hover: selected tips
        "selectedLabelStyle": "bold",
        "selectedTipGrowthFactor": "1",
        "selectedTipFillColor": "#004d65",
        "selectedTipMinSize": "5",
        "selectedTipFillOpacity": "0.5",
        "selectedTipStrokeColor": "#00364a",
        "selectedTipStrokeWidth": "1",
        "selectedTipStrokeOpacity": "0.5",
        // Selection & Hover: MRCA node
        "selectedNodeGrowthFactor": "1",
        "selectedNodeFillColor": "#831100",
        "selectedNodeMinSize": "5",
        "selectedNodeFillOpacity": "0.5",
        "selectedNodeStrokeColor": "#5c0700",
        "selectedNodeStrokeWidth": "0.5",
        "selectedNodeStrokeOpacity": "0.5",
        // Selection & Hover: tip hover
        "tipHoverGrowthFactor": "2.5",
        "tipHoverFillColor": "#f5a700",
        "tipHoverMinSize": "6",
        "tipHoverFillOpacity": "0.5",
        "tipHoverStrokeColor": "#f5a700",
        "tipHoverStrokeWidth": "0.5",
        "tipHoverStrokeOpacity": "0",
        // Selection & Hover: node hover
        "nodeHoverGrowthFactor": "2.5",
        "nodeHoverFillColor": "#f5a700",
        "nodeHoverMinSize": "6",
        "nodeHoverFillOpacity": "0.5",
        "nodeHoverStrokeColor": "#f5a700",
        "nodeHoverStrokeWidth": "0.5",
        "nodeHoverStrokeOpacity": "0",
    };

export const THEMES = {
    "Monochrome": { 
        inherit: '',
    },
    "Artic": {
        inherit: '',
        canvasBgColor: '#02292e',
        branchColor: '#19A699',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#f7eeca',
        tipSize: '3',
        tipShapeColor: '#B58901',
        tipHaloSize: '1',
        tipShapeBgColor: '#02292e',
        nodeSize: '0',
        nodeShapeColor: '#E06961',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#02292e',
        nodeBarsColor: '#E06961',
        legendTextColor: '#f7eeca',
        axisColor: '#f7eeca',
        rttRegressionColor: '#19A699',
        rttStatsBgColor: '#011a1f',
        rttStatsTextColor: '#f7eeca',
        rttAxisColor: '#f7eeca',
        typeface: 'Helvetica Neue',
        typefaceStyle: 'Thin',
        // Selection & Hover: selected tips
        "selectedTipFillColor": "#B58901",
        "selectedTipStrokeColor": "#f7eeca",
        // Selection & Hover: MRCA node
        "selectedNodeFillColor": "#E06961",
        "selectedNodeStrokeColor": "#f7eeca",
        // Selection & Hover: tip hover
        "tipHoverFillColor": "#f5a700",
        "tipHoverStrokeColor": "#f5a700",
        // Selection & Hover: node hover
        "nodeHoverFillColor": "#f5a700",
        "nodeHoverStrokeColor": "#f5a700",
    },
    "BEAST": {
        canvasBgColor: '#02292e',
        branchColor: '#68a3bb',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#B1CBB8',
        tipSize: '3',
        tipShapeColor: '#CBB944',
        tipHaloSize: '1',
        tipShapeBgColor: '#02292e',
        nodeSize: '0',
        nodeShapeColor: '#3B6F84',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#02292e',
        nodeBarsColor: '#CBB944',
        legendTextColor: '#B1CBB8',
        axisColor: '#B1CBB8',
        rttRegressionColor: '#68a3bb',
        rttStatsBgColor: '#011a1e',
        rttStatsTextColor: '#B1CBB8',
        rttAxisColor: '#B1CBB8',
        typeface: 'Monospace',
        selectedTipFillColor: '#FFF4A9',
        selectedTipStrokeColor: '#FFF4A9',
        selectedNodeFillColor: '#B1CBB8',
        selectedNodeStrokeColor: '#B1CBB8',
    },
    "O'Toole": {
        canvasBgColor: '#f4f3f3',
        branchColor: '#7984BC',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#7984BC',
        tipSize: '3',
        tipShapeColor: '#AF808B',
        tipHaloSize: '1',
        tipShapeBgColor: '#D8D4D3',
        nodeSize: '2',
        nodeShapeColor: '#88B2BA',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#D8D4D3',
        nodeBarsColor: '#88B2BA',
        legendTextColor: '#7984BC',
        axisColor: '#7984BC',
        rttRegressionColor: '#88B2BA',
        rttStatsBgColor: '#dddcdb',
        rttStatsTextColor: '#7984BC',
        rttAxisColor: '#7984BC',
        typeface: 'Helvetica Neue',
        typefaceStyle: 'Light',
        selectedTipFillColor: '#7f3e4d',
        selectedTipStrokeColor: '#7f3e4d',
        selectedNodeFillColor: '#263b3f',
        selectedNodeStrokeColor: '#263b3f',
        tipHoverFillColor: '#7f3e4d',
        tipHoverStrokeColor: '#7f3e4d',
        nodeHoverFillColor: '#263b3f',
        nodeHoverStrokeColor: '#263b3f',
    },
    // Deep jewel tones: The Life Aquatic / Isle of Dogs palette
    "MCM": {
        canvasBgColor: '#1e2d3a',
        branchColor: '#edd59c',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#f4c9a8',
        tipSize: '4',
        tipShapeColor: '#e07b65',
        tipHaloSize: '1',
        tipShapeBgColor: '#1e2d3a',
        nodeSize: '3',
        nodeShapeColor: '#7dbfcc',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#1e2d3a',
        nodeBarsColor: '#7dbfcc',
        legendTextColor: '#edd59c',
        axisColor: '#edd59c',
        rttRegressionColor: '#7dbfcc',
        rttStatsBgColor: '#121c24',
        rttStatsTextColor: '#edd59c',
        rttAxisColor: '#edd59c',
        typeface: 'Monospace',
    },
    // Royal Tenenbaums: aged plaster, forest green, burgundy, tennis-ball gold
    "Tenenbaums": {
        canvasBgColor: '#f0e8d8',
        branchColor: '#2b4a2a',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#1c3220',
        tipSize: '3',
        tipShapeColor: '#a01830',
        tipHaloSize: '1',
        tipShapeBgColor: '#f0e8d8',
        nodeSize: '2',
        nodeShapeColor: '#c8a020',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#f0e8d8',
        nodeBarsColor: '#a01830',
        legendTextColor: '#2b4a2a',
        axisColor: '#2b4a2a',
        rttRegressionColor: '#2b4a2a',
        rttStatsBgColor: '#d8cfbf',
        rttStatsTextColor: '#1c3220',
        rttAxisColor: '#2b4a2a',
        typeface: 'Monospace',
    },
    // The Darjeeling Limited: warm cream, saffron, cerulean, rust
    "Darjeeling": {
        canvasBgColor: '#faf0d8',
        branchColor: '#c87010',
        branchWidth: '1',
        fontSize: '11',
        labelColor: '#3a2010',
        tipSize: '4',
        tipShapeColor: '#1a5878',
        tipHaloSize: '1',
        tipShapeBgColor: '#faf0d8',
        nodeSize: '0',
        nodeShapeColor: '#c04428',
        nodeHaloSize: '1',
        nodeShapeBgColor: '#faf0d8',
        nodeBarsColor: '#1a5878',
        legendTextColor: '#3a2010',
        axisColor: '#3a2010',
        rttRegressionColor: '#c87010',
        rttStatsBgColor: '#e8d8c0',
        rttStatsTextColor: '#3a2010',
        rttAxisColor: '#3a2010',
        typeface: 'Monospace',
    },
};

